# Generated by Django 4.2.11 on 2024-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_bid_bid_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
